### ISSUE TITLE
Text generation

### ISSUE THREAD

**Issue by srikarym** [mahmoodlab/TITAN#1]
Hello,
Thank you for open-sourcing the models. Can TITAN be used for text generation (ROI / slide level)? [Previously](https://github.com/mahmoodlab/CONCH/issues/18), we couldn't use CONCH for generation because the public release lacked the COCA decoder weights.

**Comment by andrewsong90** [comment]
Hi @srikarym 

Thanks for your interest in TITAN. Due to hospital regulation, we cannot release the text decoder just yet. 
We are working hard to make it possible at the moment! We will keep everyone updated on this.
