### ISSUE TITLE
attn_mask dtype to be bool or to match query dtype？

### ISSUE THREAD

**Issue by cuppersd** [mahmoodlab/TITAN#11]
x = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_bias, dropout_p=self.attn_drop_prob)
RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but got attn_mask.dtype: float and  query.dtype: struct c10::BFloat16 instead.

**Comment by HHenryD** [comment]
Hi, @cuppersd 

Thanks for your question. What was the command you used?

**Comment by andrewsong90** [comment]
Hi @cuppersd 

I will close the issue for now, feel free to re-open it once you are back.

Thanks,
