### ISSUE TITLE
feature extraction: CLAM does not support conch_v1_5

### ISSUE THREAD

**Issue by dannybarash7** [mahmoodlab/TITAN#12]
Hello, 
I'm working on extracting features for my own histology data, based on `notebooks/inference_demo.ipynb`.

The reademe says:
_

> Patch feature extraction [CLAM](https://github.com/mahmoodlab/CLAM) can also be used for patch feature extraction with CONCHv1.5. When using extract_features_fp.py, set --model_name to 'conch_v1_5'.

_

it seems that CLAM does not support `conch_v1_5` yet.  And trying to use 'conch_v1' does not seem give the required 'patch_size_level0' attribute:

```
file = h5py.File(demo_h5_path, 'r')
features = torch.from_numpy(file['features'][:])
coords = torch.from_numpy(file['coords'][:])
patch_size_lv0 = file['coords'].attrs['patch_size_level0']
```

Any help/code samples would be much appreciated, and I can supply the full colab notebook if needed.

Thanks,
Danny.

**Comment by andrewsong90** [comment]
Hi @dannybarash7,

So `conch_v1_5` has been integrated into CLAM (you can look at implementation [here](https://github.com/mahmoodlab/CLAM/blob/f1e93945d5f5ac6ed077cb020ed01cf984780a77/models/builder.py#L57)). 

As mentioned in the reply to previous issue #6, you will need to supply your own `patch_size_level0` attribute, even if you use CONCHv1.5 from CLAM. Just make sure that it's 1024 for 40x and 512 for 20x!

Hope this helps!
Andrew
