### ISSUE TITLE
How to deal with the situation when the 2 results contradict each other in the actual prediction?

### ISSUE THREAD

**Issue by ghhhp** [mahmoodlab/TITAN#13]
Thank you for share this significant work!
The WSI classification and report generation involved in the article are the results of 2 task heads respectively, in essence, we surely want the description of the report to be consistent with the specific classification, but it seems that we don't see any description of the consistency of these two results in the article, and I would like to ask you how to ensure the consistency of the content? How to deal with the situation when the 2 results contradict each other in the actual prediction?

**Comment by andrewsong90** [comment]
Hi @ghhhp 

Thanks for the great question. Actually, we have not checked the results of the classification head and the text decoder simultaneously. As of now, I would trust the classification results with more confidence as report generation is considerably harder and will need to be developed/refined further.

Best,
Andrew
