### ISSUE TITLE
Can the current titan be used to generate pathology reports？

### ISSUE THREAD

**Issue by Eason215xB** [mahmoodlab/TITAN#14]
Thank you for your work. It's great.
I want to know whether the current code can support titan to generate pathological reports. If I input a picture, titan will generate the corresponding report. What I want to know is whether the improved pathology report in the paper is the generated report or the classification corresponding to the input text.

**Comment by andrewsong90** [comment]
Hi @Eason215xB 

TITAN does have text decoder for report generation, which we haven't released for the initial preview version. We are internally working on to improve the performance & make sure everything complies with the clinical regulation. 
Right now, TITAN-preview only has vision and text encoders.

In the paper, we tried to be explicit on whether the example text is generated or written by pathologists.

Hope this helps,
Andrew
