### ISSUE TITLE
heatmap visualization

### ISSUE THREAD

**Issue by ghhhp** [mahmoodlab/TITAN#15]
Hi，I want to plot the whole slide heatmap of conch v1.5, is it possible to get the similarity by F.cosine_similarity(image_embedings, text_embedings) or (image_embedings @ text_embedings.T * model.logit_scale. exp()) to get the similarity of each patch in the whole slide, and then map back to where the patches are located. Is it feasible to map the heatmap effect this way? Can you provide more details on this piece? Thanks!

**Comment by andrewsong90** [comment]
Hi @ghhhp 

Yes, what you are proposing seems reasonable to me mechanism-wise. 
In a very different context (non VL), I've done it previously (construct a WSI heatmap based on similarity score to a different representative embedding) in Figure 1 of [PANTHER](https://openaccess.thecvf.com/content/CVPR2024/papers/Song_Morphological_Prototyping_for_Unsupervised_Slide_Representation_Learning_in_Computational_Pathology_CVPR_2024_paper.pdf).

Having said that, you might want to be careful if you are extracting text embeddings with TITAN's text decoder. The text decoder is from Stage 3, which means it takes in pathology report that is a coarse description of the entire WSI. Therefore, computing similarity between image patch embeddings (of fine-grained morphology) and text embedding (coarse description) might be mismatch.

Best,
Andrew
