### ISSUE TITLE
How to deal with a large WSI input

### ISSUE THREAD

**Issue by zhangjing9701** [mahmoodlab/TITAN#16]
Hi, thanks for your wonderful work!

When I input a large-size WSI (EBRAINS dataset), "CUDA OUT MEMORY" error will occured.  How to deal with this issue? Change a better GPU, or, other flexible solutions.
![Quicker_20241230_171459](https://github.com/user-attachments/assets/ce4abcbf-fd9b-4e5b-b6f4-e4ad0fa5826e)

Thanks very much!

**Comment by zhtyolivia** [comment]
Hi, how did you eventually solve this problem? Thank you!
