### ISSUE TITLE
Another feature sizes

### ISSUE THREAD

**Issue by PabloMeseguerEsbri** [mahmoodlab/TITAN#2]
Outstanding work, looks amazing!

Thie preview of TITAN can be extended to be used as slide-level encoder of CONCH features of length 512?

Thanks in advance!

**Comment by PabloMeseguerEsbri** [comment]
I was not referring to the number of patches in each WSI. In the demo example the size of the features is [N,L] being N the number of patches (variable for each WSI) and L=768 (latent space length of CONCH v1.5). However, the output size of the original CONCH model was L=512. It makes sense to use these old CONCH features ([N,512]) to obtain the slide-level aggregation with TITAN?

**Comment by andrewsong90** [comment]
Yes, CONCHv1.5 feature dimension is 768 (different from original CONCH's 512) and TITAN is entirely pretrained on CONCHv1.5 features, so it won't be compatible. Therefore, to use TITAN you will have to re-extract feature embeddings for each patch using CONCHv1.5 (also available in [hugging face](https://huggingface.co/MahmoodLab/TITAN)).

We are also looking at uploading patch features for public datasets, such as TCGA, so stay tuned.

**Comment by PabloMeseguerEsbri** [comment]
Thank you for the upload!
