### ISSUE TITLE
Conch 1.5 Integration with CLAM Repository

### ISSUE THREAD

**Issue by FabianHoerst** [mahmoodlab/TITAN#4]
Hello, 

I attempted to use the pipeline on a new dataset but noticed that Conch 1.5 is not yet included in the CLAM repository. Is there any plan to integrate Conch 1.5 into the repository? Alternatively, is there a script available to generate the patch-level embeddings beforehand or guides on how to get the conch 1.5 features?

Thanks in advance!

**Comment by PabloMeseguerEsbri** [comment]
I followed the guide on the CONCH Github and tried to replicate with CONCHv1.5 from TITAN. This is the code snippet I used to read the images from CLAM .h5 files and to obtain the patch-level embeddings. Performance on an in-house dataset is consistent (slightly better than CONCH), so assuming that it is well implemented. xD

```
titan = AutoModel.from_pretrained('MahmoodLab/TITAN', trust_remote_code=True)
conch, eval_transform = titan.return_conch()
conch.cuda()
with h5py.File(os.path.join(folder, name_wsi + ".h5"), 'r') as file:
    images = file['imgs'][:]
    coords = file['coords'][:]
images = [Image.fromarray(patch) for patch in images]
patch_embeddings = []
for img in tqdm(images):
    img = eval_transform(img).unsqueeze(dim=0).cuda()
    with torch.inference_mode():
        x = conch(img).squeeze().cpu().numpy()
    patch_embeddings.append(x)
patch_embeddings = np.stack(patch_embeddings)
```

**Comment by FabianHoerst** [comment]
Hi @PabloMeseguerEsbri 

could you specify the setting for the patch extraction then such that I can compare them to mine?
Thanks for your fast response. I was following a similar approach, but I am curious how you get the images in your h5 file.

Best, Fabian

**Comment by PabloMeseguerEsbri** [comment]
With the setting do you mean a particular custom downsample factor and patch/step size? In the paper, they recommend to use 20x magnification and 512x512 patches.

**Comment by andrewsong90** [comment]
Hi @FabianHoerst 

We are looking into this and will get back to you shortly about the integration into CLAM.

As @PabloMeseguerEsbri rightly mentions, TITAN is pretrained on 512x512 pixel patches at 20x magnification, so you should also patch with that setting.

Best,
Andrew

**Comment by FabianHoerst** [comment]
Ok thank you very much, I extracted at 1024x1024 on x40 and then used your transformations. According to your conch settings from HF, I just used your eval_transforms then on the 1024x1024 patches, as they incorporate a resize operation:
```python
Compose(
    Resize(size=448, interpolation=bilinear, max_size=None, antialias=warn)
    CenterCrop(size=(448, 448))
    ToTensor()
    Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
)
```
I think this should work.

**Comment by andrewsong90** [comment]
Dear everyone,

We have no integrated CONCHv1.5 feature extraction into CLAM.
Take a look at the updated readme

Thanks!
