### ISSUE TITLE
Getting slide embeddings from TITAN for custom dataset. 

### ISSUE THREAD

**Issue by mertikinci** [mahmoodlab/TITAN#5]
Hey hey,

First of all thank you for such a great work, engineering and all the effort, it will open up another way for pathology for sure. 

Secondly, I am currently working on my thesis about a classification task working on histopathological images. My dataset includes whole slide biopsy images from eye, and individual crops from different ROI's on the whole slides. And I aim to extract meaningful features for those crops to enhance the performance of my model. I am particularly interested in leveraging TITAN's capabilities to generate slide-level embeddings for my custom dataset.

I have 2 questions in the light of that: 

1. How to prepare and format a custom dataset with raw images only to use TITAN for feature extraction?

in the `inference_demo.py ` it seems like we are giving **features, coords and patch_size**, what are those exactly and how can I get them for my custom dataset? What exactly are the prior steps to do with a dataset to use them like  at ` inference_demo.py` ?

2. Is there any specific parameters or configurations in TITAN that I need to adjust for my use case?

Additionally, if there are any prerequisites or example workflows that demonstrate embedding extraction for a custom dataset, I would appreciate it if you could share them.

**Comment by FabianHoerst** [comment]
Hi, maybe follow this discussion: https://github.com/mahmoodlab/TITAN/issues/4

**Comment by andrewsong90** [comment]
Hi @mertikinci 

As @FabianHoerst mentioned, you can use CONCHv1.5 patch feature extraction (either through your custom data loader or using [CLAM](https://github.com/mahmoodlab/CLAM)) to get the patch features on 512x512 patches at 20X magnification. These are then what is fed into slide inference process which is described in inference_demo.py.

As for 1, we encourage you take a look/adapt from CLAM for patch feature extraction.

Best,
