### ISSUE TITLE
Error with missing 'patch_size_level0' attribute in HDF5 files when using custom dataset with CLAM and TITAN

### ISSUE THREAD

**Issue by rzuberi** [mahmoodlab/TITAN#6]
Hi,

I encountered an issue while implementing the example for the TITAN model from the `MahmoodLab/TITAN` repository on Hugging Face. When replacing the example dataset with my custom dataset of patches generated using CLAM, I encountered the following error:

`KeyError: "Unable to synchronously open attribute (can't locate attribute: 'patch_size_level0')"`

**Steps to Reproduce**
Run the following code to load the model and process HDF5 data:

```
import h5py
from transformers import AutoModel
import torch

# Load model
titan = AutoModel.from_pretrained('MahmoodLab/TITAN', trust_remote_code=True)

# Load custom dataset HDF5 file
h5_path = 'one_of_my_CLAM_patched_WSIs.h5'
with h5py.File(h5_path, 'r') as file:
    features = torch.from_numpy(file['features'][:])
    coords = torch.from_numpy(file['coords'][:])
    patch_size_lv0 = file['coords'].attrs['patch_size_level0'] # Line producing the error

# Extract slide embedding
with torch.autocast('cuda', torch.float16), torch.inference_mode():
    slide_embedding = titan.encode_slide_from_patch_features(features, coords, patch_size_lv0)
```

**Observations**

- The patch_size_level0 attribute exists in the provided TCGA demo dataset (TCGA_demo_features).
- This issue arises because the CLAM project does not generate a patch_size_level0 attribute when creating HDF5 files.
- Without this attribute, the encode_slide_from_patch_features method in TITAN cannot proceed.

**Workaround Attempted**
As a temporary solution, I manually added the missing attribute to the HDF5 file:

with h5py.File('one_of_my_CLAM_patched_WSIs.h5', 'a') as file:
    file['coords'].attrs['patch_size_level0'] = 1024

**Comment by andrewsong90** [comment]
Hi @rzuberi 

Yes, you are correct in that CLAM doesn't readily provide `patch_size_level0`, as we wanted to maintain the design of CLAM to be a generic patch feature encoder. After all `patch_size_level0` is a property required for TITAN, not an output of CONCHv1.5. 

So yes, you will need to explicitly provide the attribute yourself. You can either save it in .h5 files as you show in the workaround, or simply supply it as an argument when running `titan.encode_slide_from_patch_features` function. Just make sure that it's 1024 for 40x and 512 for 20x!

We will update the readme/notebook soon to prevent any possible confusion.

Thanks!

**Comment by tulvgengenr** [comment]
> Hi [@rzuberi](https://github.com/rzuberi)
> 
> Yes, you are correct in that CLAM doesn't readily provide `patch_size_level0`, as we wanted to maintain the design of CLAM to be a generic patch feature encoder. After all `patch_size_level0` is a property required for TITAN, not an output of CONCHv1.5.
> 
> So yes, you will need to explicitly provide the attribute yourself. You can either save it in .h5 files as you show in the workaround, or simply supply it as an argument when running `titan.encode_slide_from_patch_features` function. Just make sure that it's 1024 for 40x and 512 for 20x!
> 
> We will update the readme/notebook soon to prevent any possible confusion.
> 
> Thanks!

Hi @andrewsong90 ～
If my WSI's level0 magnification is 40x and level1 magnification is 20x, to accommodate TITAN's requirement of 20x for the data, I specify the `patch_level` to be 1 when I use CLAM's create patches, the full command is below:
```python
python create_patches_fp.py \
    --source “$current_dir” \
    --save_dir “$save_dir_base” \
    --patch_size 512 \
    --step_size 512 \
    --seg \
    --preset liver_custom.csv \
    --patch \
    --stitch \
    --patch_level 1 \
```

Should I set `patch_size_lv0` to 512 when feeding into Slide Encoder after extracting patch features?

**Comment by andrewsong90** [comment]
Hi @tulvgengenr 

In this case, you should set `patch_size_lv0` to 1024, since the original coordinates from CLAM will be saved at 40x. The goal of this parameter is to provide _reference_ for TITAN when it tries to perform ALiBi positional encoding - it always assumes 512px patch size at 20x.

To double check, you can check the `coordinates` attribute of the contiguous patches extracted from CLAM and verify that the coordinate displacement (either in x or y direction) is 1,024.

Hope this helps.
