### ISSUE TITLE
Incompatibility with numpy version 2.0.2

### ISSUE THREAD

**Issue by edwhere** [mahmoodlab/TITAN#7]
The recommended "pip install -e ." command installed numpy version 2.0.2 in my machine (Ubuntu  22.04).

After installation, I tried running the inference example, but it gives the following error: 

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

The solution that worked in my case is to downgrade numpy to version 1.26.4

**Comment by andrewsong90** [comment]
Hi @edwhere 

Thank you for letting us know - We weren't aware of the version clash. We will look into fixing this in the next iteration.
