### ISSUE TITLE
Reproducibility of slide embedding

### ISSUE THREAD

**Issue by iamownt** [mahmoodlab/TITAN#8]
Thank you for your outstanding work! I’ve noticed a performance boost compared to other models like UNI, CONCH, and Prov-Gigapath. However, I've encountered an issue when extracting features from TCGA-NSCLC slides at 512x512 pixels with 20x magnification. My slide embeddings seem to be of lower quality than those generated officially. For instance, under a custom 20-split configuration, my reproducible results(accuracy, auroc) are (0.9329/0.9767), compared to the official embedding’s (0.9355/0.9764). I suspect this discrepancy may be due to differences in the slide preprocessing stage, but it seems that CLAM can not set 20x magnification when tiling (it only supports patch_level:)? https://github.com/mahmoodlab/CLAM/blob/master/create_patches.py

Do you have any suggestions? Specifically, when generating tile embeddings, do you use 512x512 resolutions and then crop them to 448x448, or do you directly feed 512x512 into your tile models during the transform stage?

Thank you for your guidance!

**Comment by andrewsong90** [comment]
Hi @iamownt,

In my mind, the two sets of the numbers you are reporting all quite similar to each other, so I wouldn't call your embeddings low-quality at all. The reason for discrepancy (other than the seeds/different environments) can be from segmentation/preprocessing stage as you rightly mentioned. 

For CLAM, yes you cannot explicitly set the explicit magnification level (only patch level), so you will need to make sure for each slide that you are correctly patching at 20x mangification at 512x512 pixel size (Or 1024x1024 if 40x mangnification). So the discrepancy could be wrong magnification level for some slides.

For inference with patch features, we always feed 512x512 patch directly and it will get resized to 448x448 (So no explicit cropping happening).

Hope this helps,
