### ISSUE TITLE
No such file or directory:'root/.cache/haggingface/modules/transformers_modules/conch_tokenizer.py

### ISSUE THREAD

**Issue by ghhhp** [mahmoodlab/TITAN#9]
I've already installed transformer==4.46.0,but when I use "AutoModel.from_pretrained(local，trust_remote_code=True)", some error happened:  No such file or directory:'root/.cache/haggingface/modules/transformers_modules/conch_tokenizer.py.
I'm using this program in a network-less environment，thanks!

**Comment by andrewsong90** [comment]
Hi @ghhhp 

Thanks for raising this issue. 
For now, I think the best solution is to manually copy `conch_tokenizer.py` to the directory `root/.cache/haggingface/modules/transformers_modules/`

Hope this helps,
